import SvgIcon from "@/components/svg-icon";

export const INSTAGRAM_SERVICES = [
   {
      id: 1,
      // sort: 0,
      title: "Photos",
      icon: <SvgIcon name={"brands/instagram/photos"} />,
      type: "posts",
      params: {
         index: "",
         type: "photos",
      },
      placeholder: "Enter a post link or photos link, example = ...",
      is_active: false,
      brand: "instagram",
      site: "main",
   },
   {
      id: 2,
      // sort: 1,
      title: "Videos",
      icon: <SvgIcon name={"brands/instagram/videos"} />,
      type: "posts",
      params: {
         index: "",
         type: "videos",
      },
      placeholder: "Enter a post link or video link, example = ...",
      is_active: false,
      brand: "instagram",
      site: "main",
   },
   {
      id: 3,
      // sort: 2,
      title: "Profile",
      icon: <SvgIcon name={"brands/instagram/profile"} />,
      type: "profile",
      params: {
         index: "",
         type: "profile",
      },
      placeholder: "Enter a username or profile link, example = ...",
      is_active: false,
      brand: "instagram",
      site: "main",
   },
   {
      id: 4,
      // sort: 3,
      title: "IGTVs",
      icon: <SvgIcon name={"brands/instagram/igtvs"} />,
      type: "igtvs",
      params: {
         index: "",
         type: "igtvs",
      },
      placeholder: "Enter a igtv link or post link, example = ...",
      is_active: false,
      brand: "instagram",
      site: "main",
   },
   {
      id: 5,
      // sort: 4,
      title: "Reels",
      icon: <SvgIcon name={"brands/instagram/reels"} />,
      type: "reels",
      params: {
         index: "",
         type: "reels",
      },
      placeholder: "Enter a reels link or post link, example = ...",
      is_active: false,
      brand: "instagram",
      site: "main",
   },
   {
      id: 6,
      // sort: 5,
      title: "Profile Picture",
      icon: <SvgIcon name={"brands/instagram/profile-picture"} />,
      type: "profile",
      params: {
         index: "",
         type: "profile_picture",
      },
      placeholder: "Enter a username or profile link, example = ...",
      is_active: false,
      brand: "instagram",
      site: "main",
   },
   {
      id: 7,
      // sort: 6,
      title: "Stories",
      icon: <SvgIcon name={"brands/instagram/stories"} />,
      type: "stories",
      params: {
         index: "",
         type: "stories",
      },
      placeholder: "Enter a username or story link, example = ...",
      is_active: true,
      brand: "instagram",
      site: "main",
   },
   {
      id: 8,
      // sort: 7,
      title: "Posts",
      icon: <SvgIcon name={"brands/instagram/posts"} />,
      type: "posts",
      params: {
         index: "",
         type: "posts",
      },
      placeholder: "Enter a post link, example = ...",
      is_active: false,
      brand: "instagram",
      site: "main",
   },
   {
      id: 9,
      // sort: 8,
      title: "Highlights",
      icon: <SvgIcon name={"brands/instagram/highlights"} />,
      type: "highlights",
      params: {
         index: "",
         type: "highlights",
      },
      placeholder: "Enter a username or highlight link, example = ...",
      is_active: false,
      brand: "instagram",
      site: "main",
   },
];
